### ISSUE TITLE
docker image doesn't work [TFramedTransportFactory missing] 

### ISSUE THREAD

**Issue by fruch** [CodeLieutenant/cassandra-stress#7]
can't start any command, with any of the images up in dockerhub:

```bash
❯ docker run scylladb/cassandra-stress:latest cassandra-stress write
java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/TFramedTransportFactory
        at org.apache.cassandra.stress.settings.SettingsTransport$TOptions.<init>(SettingsTransport.java:132)
        at org.apache.cassandra.stress.settings.SettingsTransport.get(SettingsTransport.java:159)
        at org.apache.cassandra.stress.settings.StressSettings.get(StressSettings.java:293)
        at org.apache.cassandra.stress.settings.StressSettings.parse(StressSettings.java:243)
        at org.apache.cassandra.stress.Stress.run(Stress.java:80)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.thrift.TFramedTransportFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 6 more
```

also when I built it myself:
```bash
❯ docker build . -t ttt --build-arg CASSANDRA_STRESS_VERSION=1.2.3
...

❯ docker run ttt cassandra-stress write
java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/TFramedTransportFactory
        at org.apache.cassandra.stress.settings.SettingsTransport$TOptions.<init>(SettingsTransport.java:132)
        at org.apache.cassandra.stress.settings.SettingsTransport.get(SettingsTransport.java:159)
        at org.apache.cassandra.stress.settings.StressSettings.get(StressSettings.java:293)
        at org.apache.cassandra.stress.settings.StressSettings.parse(StressSettings.java:243)
        at org.apache.cassandra.stress.Stress.run(Stress.java:80)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.thrift.TFramedTransportFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 6 more
```

docker version I'm using locally:

```bash
❯ docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:01 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by CodeLieutenant** [comment]
Fixes in v3.12.1

Missing classes from Apache Thrift
